version: ´3´
services:
  app01:
    container_name: api01
    image: nmatsui/hello-world-api
    ports:
      -3000:3000

  app02:
    container_name: api02
    image: nmatsui/hello-world-api
    ports:
      -3000:3000

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydatabase